version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: support_db
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password_prueba
      POSTGRES_DB: support_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: