services:
  postgres:
    image: postgres:15-alpine
    container_name: support_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-support_platform}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - support-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: support_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres_user}
      - DB_PASSWORD=${DB_PASSWORD:-password123}
      - DB_NAME=${DB_NAME:-support_platform}
      - JWT_SECRET=${JWT_SECRET:-tockenDePrueba132}
    depends_on:
      - postgres
    networks:
      - support-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: support_frontend
    restart: always
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - support-network

volumes:
  pgdata:

networks:
  support-network:
    driver: bridge